### ISSUE TITLE
Error on 'npm install' for latest master version (bb94477)

### ISSUE THREAD

**Issue by akramer-zibra** [hyperhyperspace/hyper-browser-web#4]
Hey, 
unfortunately `npm install` fails with an error:

```console
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @hyper-hyper-space/hyper-browser-web@0.1.0
npm ERR! Found: @hyper-hyper-space/core@0.10.1
npm ERR! node_modules/@hyper-hyper-space/core
npm ERR!   @hyper-hyper-space/core@"0.10.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @hyper-hyper-space/core@"0.9.0" from @hyper-hyper-space/home@0.1.0
npm ERR! node_modules/@hyper-hyper-space/home
npm ERR!   @hyper-hyper-space/home@"^0.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Achim\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Achim\AppData\Local\npm-cache\_logs\2022-07-08T14_50_11_451Z-debug.log
```

Seems `@hyper-hyper-space/home@0.1.0` wants `@hyper-hyper-space/core@0.9.0` instead of the latest `@0.10.1` ?

Branch: master
Commit:  bb94477

OS: Widnows 10
Node: 16.13.0
npm: 8.1.0

**Comment by sbazerque** [comment]
Hi @akramer-zibra ! How's it going?

I've just updated the Readme for this project to reflect that in order to run the current version, you need to check out HHS' development monorepo (that includes this repo as a submodule), I think that's what causing the error.

**Comment by akramer-zibra** [comment]
Hey @sbazerque , 
still having fun playing around with this lovely library! Thanks :-) 

I switched to the [hyperhyperspace/workspace](https://github.com/hyperhyperspace/workspace) repository and did the installation as you describe there in the [README.md](https://github.com/hyperhyperspace/workspace/blob/master/README.md). With this approach the errors disappear. 

Having your application code is a nice reference of implementation and helps me integrate the core package into my code base. Looking forward to see this project growing

**Comment by sbazerque** [comment]
That's great!

While the core library is stabilizing, there are a few changes / fixes in the repo that have not been released to NPM yet. If you eventually upgrade your project's @hyper-hyper-space/core dependency and find any incompatibilities / issues, please send a shout (either here or on Discord) and we'll help you sort it out.
